name: Image Build CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PACKAGE_NAME: memobot
  REGIS_URL: ${{ secrets.REGIS }}/${{ secrets.REGIS_USER }}/memobot

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.2.3

      - name: Build and push latest tag
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ env.REGIS_URL }}:latest

      - name: Build and push version tag
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ env.REGIS_URL }}:${{ steps.package-version.outputs.current-version }}